"""empty message

Revision ID: c4286c591592
Revises: 6e1a0bfdf4f2
Create Date: 2024-05-30 18:12:42.129300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4286c591592'
down_revision: Union[str, None] = '6e1a0bfdf4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo_biologico', sa.String(length=1), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default='now()', nullable=False),
    sa.Column('formulario', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_formulario', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('dependentes',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_dependente', sa.Integer(), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_dependente'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_dependente')
    )
    op.create_table('medicos',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('crm', sa.String(), nullable=False),
    sa.Column('especialidade', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_medicos_id_usuario'), 'medicos', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicos_id_usuario'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_table('dependentes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
